# Licensed under the MIT License.
#
# Module manifest for module 'UnityPackageArchiver'
#
# Generated by: hanachiru
#
# Generated on: 2025-02-11
#

@{
    RootModule        = 'UnityPackageArchiver'
    ModuleVersion     = '0.1.0'
    GUID              = 'e7b8f8d2-3c4b-4f5a-8a9b-123456789abc'
    Author            = 'hanachiru'
    Description       = 'PowerShell module for extracting and compressing Unity packages.'

    FunctionsToExport = @(
        'Import-UnityPackage',
        "Export-UnityPackage"
    )

    CmdletsToExport   = @()

    VariablesToExport = @()

    AliasesToExport   = @()

    PrivateData       = @{

        PSData = @{
            Tags       = 'Unity'
            LicenseUri = 'https://github.com/hanachiru/UnityPackageArchiver/blob/main/LICENSE'
            ProjectUri = 'https://github.com/hanachiru/UnityPackageArchiver'

        }
    }

    HelpInfoURI       = 'https://github.com/hanachiru/UnityPackageArchiver/blob/main/README.md'
}