name: Publish
on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        options: [major, minor, patch]
        required: true
        default: patch
        description: "The level of version bump to apply"

permissions:
  contents: read

env:
  MODULE_PATH: ./UnityPackageArchiver
  PSD1_PATH: ./UnityPackageArchiver/UnityPackageArchiver.psd1

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.ref_name == 'main'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check and Update Version
        id: update-version
        shell: pwsh
        run: |
          $PSNativeCommandUseErrorActionPreference = $true
          $ErrorActionPreference = 'Stop'

          $manifest = Test-ModuleManifest $env:PSD1_PATH
          $versionString = $manifest.Version.ToString()
          Write-Output "Current Module Version: $versionString"

          $newVersion = $manifest.Version
          switch ('${{ github.event.inputs.bump-level }}') {
              'major' { $newVersion = New-Object System.Version($([int]$manifest.Version.Major + 1), 0, 0) }
              'minor' { $newVersion = New-Object System.Version($([int]$manifest.Version.Major), $([int]$manifest.Version.Minor + 1), 0) }
              'patch' { $newVersion = New-Object System.Version($([int]$manifest.Version.Major), $([int]$manifest.Version.Minor), $([int]$manifest.Version.Build + 1)) }
          }

          Update-ModuleManifest -ModuleVersion $newVersion -Path $env:PSD1_PATH

          $newManifest = Test-ModuleManifest $env:PSD1_PATH
          $versionString = $newManifest.Version.ToString()
          Write-Host "New Module Version: $versionString"
          Write-Output "newVersion=${versionString}" | Tee-Object -FilePath ${env:GITHUB_OUTPUT} -Append
      - name: Create Pull Request
        shell: bash
        env:
          USERNAME: github-actions[bot]
          EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          BRANCH: auto/${{ github.run_id }}/${{ github.run_attempt }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "${USERNAME}"
          git config --global user.email "${EMAIL}"
          git switch -c "${BRANCH}"
          git add "${PSD1_PATH}"
          message="Update v${VERSION} at .psd1"
          git commit -m "${message}"
          git push origin "${BRANCH}"
          gh pr create --head "${BRANCH}" --title "${message}" --body "${message}"
      - name: Publish to PowerShell Gallery
        shell: pwsh
        run: |
          $PSNativeCommandUseErrorActionPreference = $true
          $ErrorActionPreference = 'Stop'

          Publish-Module -Path $env:MODULE_PATH -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }} -Repository PSGallery -Force
      - uses: release-drafter/release-drafter@v6
        id: release-drafter
        with:
          publish: true
          commitish: main
          tag: v${{ steps.update-version.outputs.newVersion }}
          name: v${{ steps.update-version.outputs.newVersion }}
          version: ${{ steps.update-version.outputs.newVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
