name: Publish
on:
  workflow_dispatch:
    inputs:
      bump-level:
        type: choice
        options: [major, minor, patch]
        required: true
        default: patch
        description: "The level of version bump to apply"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      MODULE_PATH: ./UnityPackageArchiver
      PSD1_PATH: ./UnityPackageArchiver/UnityPackageArchiver.psd1
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check and Update Version
        shell: pwsh
        run: |
          $PSNativeCommandUseErrorActionPreference = $true
          $ErrorActionPreference = 'Stop'

          $manifest = Test-ModuleManifest $env:PSD1_PATH
          $versionString = $manifest.Version.ToString()
          Write-Output "Current Module Version: $versionString"

          $newVersion = $manifest.Version
          switch (${{ github.event.inputs.bump-level }}) {
              'major' { $newVersion = New-Object System.Version($manifest.Version.Major + 1, 0, 0) }
              'minor' { $newVersion = New-Object System.Version($manifest.Version.Major, $manifest.Version.Minor + 1, 0) }
              'patch' { $newVersion = New-Object System.Version($manifest.Version.Major, $manifest.Version.Minor, $manifest.Version.Build + 1) }
          }

          Update-ModuleManifest -ModuleVersion $newVersion -Path $env:PSD1_PATH

          $manifest = Test-ModuleManifest $env:PSD1_PATH
          $versionString = $manifest.Version.ToString()
          Write-Host "New Module Version: $versionString"
      - name: Publish to PowerShell Gallery
        shell: pwsh
        run: |
          $PSNativeCommandUseErrorActionPreference = $true
          $ErrorActionPreference = 'Stop'

          Publish-Module -Path $env:MODULE_PATH -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }} -Repository PSGallery -Force
